#!/bin/sh
# Regenerate src/dmdmodules.d: the list of vendored dmd modules whose static
# variables dmdglobals.d snapshots. Run after `make vendor` (the Makefile does).
set -e
DC=${DC:-dmd}
mods=$($DC -Isrc -i -version=MARS -version=NoMain -version=GC -version=NoBackend \
  -version=CallbackAPI -version=DMDLIB -preview=dip1000 \
  -Jsrc/dmd/res -Jsrc/dmd -Jstringimp src/dmd/frontend.d -o- -deps 2>&1 \
  | grep -oE '(^| : \w+ : )dmd\.[a-zA-Z0-9_.]+ \(src/' \
  | grep -oE 'dmd\.[a-zA-Z0-9_.]+' | sort -u)
{
  echo "// GENERATED by tools/gen-dmdmodules.sh from the vendored frontend closure."
  echo "// Do not edit; rerun the script after \`make vendor\`."
  echo "module dmdmodules;"
  echo
  echo "import core.internal.traits : AliasSeq;"
  echo
  for m in $mods; do echo "static import $m;"; done
  echo
  echo "alias dmdModules = AliasSeq!("
  for m in $mods; do echo "    $m,"; done
  echo ");"
} > src/dmdmodules.d
echo "src/dmdmodules.d: $(echo "$mods" | wc -l) modules"
