// GENERATED by tools/gen-dmdmodules.sh from the vendored frontend closure.
// Do not edit; rerun the script after `make vendor`.
module dmdmodules;

import core.internal.traits : AliasSeq;

static import dmd.access;
static import dmd.aggregate;
static import dmd.aliasthis;
static import dmd.argtypes_aarch64;
static import dmd.argtypes_sysv_x64;
static import dmd.argtypes_x86;
static import dmd.arrayop;
static import dmd.arraytypes;
static import dmd.astcodegen;
static import dmd.astenums;
static import dmd.ast_node;
static import dmd.attrib;
static import dmd.attribsem;
static import dmd.blockexit;
static import dmd.builtin;
static import dmd.canthrow;
static import dmd.chkformat;
static import dmd.clone;
static import dmd.common.bitfields;
static import dmd.common.charactertables;
static import dmd.common.file;
static import dmd.common.identifiertables;
static import dmd.common.outbuffer;
static import dmd.common.smallbuffer;
static import dmd.compiler;
static import dmd.cond;
static import dmd.console;
static import dmd.constfold;
static import dmd.cparse;
static import dmd.ctfeexpr;
static import dmd.ctorflow;
static import dmd.dcast;
static import dmd.dclass;
static import dmd.declaration;
static import dmd.delegatize;
static import dmd.denum;
static import dmd.deps;
static import dmd.dfa.entry;
static import dmd.dfa.fast.analysis;
static import dmd.dfa.fast.expression;
static import dmd.dfa.fast.report;
static import dmd.dfa.fast.statement;
static import dmd.dfa.fast.structure;
static import dmd.dfa.utils;
static import dmd.dimport;
static import dmd.dinifile;
static import dmd.dinterpret;
static import dmd.dmacro;
static import dmd.dmdparams;
static import dmd.dmodule;
static import dmd.doc;
static import dmd.dscope;
static import dmd.dstruct;
static import dmd.dsymbol;
static import dmd.dsymbolsem;
static import dmd.dtemplate;
static import dmd.dversion;
static import dmd.entity;
static import dmd.enumsem;
static import dmd.errors;
static import dmd.errorsink;
static import dmd.escape;
static import dmd.expression;
static import dmd.expressionsem;
static import dmd.file_manager;
static import dmd.func;
static import dmd.funcsem;
static import dmd.globals;
static import dmd.hdrgen;
static import dmd.id;
static import dmd.identifier;
static import dmd.impcnvtab;
static import dmd.imphint;
static import dmd.importc;
static import dmd.init;
static import dmd.initsem;
static import dmd.intrange;
static import dmd.json;
static import dmd.lambdacomp;
static import dmd.lexer;
static import dmd.location;
static import dmd.mangle;
static import dmd.mangle.basic;
static import dmd.mangle.cpp;
static import dmd.mangle.cppwin;
static import dmd.mtype;
static import dmd.mustuse;
static import dmd.nogc;
static import dmd.nspace;
static import dmd.ob;
static import dmd.objc;
static import dmd.opover;
static import dmd.optimize;
static import dmd.parse;
static import dmd.pragmasem;
static import dmd.printast;
static import dmd.root.aav;
static import dmd.root.array;
static import dmd.root.bitarray;
static import dmd.root.complex;
static import dmd.root.ctfloat;
static import dmd.root.env;
static import dmd.root.file;
static import dmd.root.filename;
static import dmd.root.hash;
static import dmd.root.longdouble;
static import dmd.rootobject;
static import dmd.root.optional;
static import dmd.root.port;
static import dmd.root.region;
static import dmd.root.rmem;
static import dmd.root.speller;
static import dmd.root.string;
static import dmd.root.stringtable;
static import dmd.root.utf;
static import dmd.safe;
static import dmd.semantic2;
static import dmd.semantic3;
static import dmd.sideeffect;
static import dmd.statement;
static import dmd.statementsem;
static import dmd.staticassert;
static import dmd.staticcond;
static import dmd.stmtstate;
static import dmd.target;
static import dmd.targetcompiler;
static import dmd.templateparamsem;
static import dmd.templatesem;
static import dmd.timetrace;
static import dmd.tokens;
static import dmd.traits;
static import dmd.typesem;
static import dmd.typinf;
static import dmd.utils;
static import dmd.visitor;
static import dmd.visitor.foreachvar;
static import dmd.visitor.parsetime;
static import dmd.visitor.permissive;
static import dmd.visitor.postorder;
static import dmd.visitor.statement_rewrite_walker;
static import dmd.visitor.transitive;

alias dmdModules = AliasSeq!(
    dmd.access,
    dmd.aggregate,
    dmd.aliasthis,
    dmd.argtypes_aarch64,
    dmd.argtypes_sysv_x64,
    dmd.argtypes_x86,
    dmd.arrayop,
    dmd.arraytypes,
    dmd.astcodegen,
    dmd.astenums,
    dmd.ast_node,
    dmd.attrib,
    dmd.attribsem,
    dmd.blockexit,
    dmd.builtin,
    dmd.canthrow,
    dmd.chkformat,
    dmd.clone,
    dmd.common.bitfields,
    dmd.common.charactertables,
    dmd.common.file,
    dmd.common.identifiertables,
    dmd.common.outbuffer,
    dmd.common.smallbuffer,
    dmd.compiler,
    dmd.cond,
    dmd.console,
    dmd.constfold,
    dmd.cparse,
    dmd.ctfeexpr,
    dmd.ctorflow,
    dmd.dcast,
    dmd.dclass,
    dmd.declaration,
    dmd.delegatize,
    dmd.denum,
    dmd.deps,
    dmd.dfa.entry,
    dmd.dfa.fast.analysis,
    dmd.dfa.fast.expression,
    dmd.dfa.fast.report,
    dmd.dfa.fast.statement,
    dmd.dfa.fast.structure,
    dmd.dfa.utils,
    dmd.dimport,
    dmd.dinifile,
    dmd.dinterpret,
    dmd.dmacro,
    dmd.dmdparams,
    dmd.dmodule,
    dmd.doc,
    dmd.dscope,
    dmd.dstruct,
    dmd.dsymbol,
    dmd.dsymbolsem,
    dmd.dtemplate,
    dmd.dversion,
    dmd.entity,
    dmd.enumsem,
    dmd.errors,
    dmd.errorsink,
    dmd.escape,
    dmd.expression,
    dmd.expressionsem,
    dmd.file_manager,
    dmd.func,
    dmd.funcsem,
    dmd.globals,
    dmd.hdrgen,
    dmd.id,
    dmd.identifier,
    dmd.impcnvtab,
    dmd.imphint,
    dmd.importc,
    dmd.init,
    dmd.initsem,
    dmd.intrange,
    dmd.json,
    dmd.lambdacomp,
    dmd.lexer,
    dmd.location,
    dmd.mangle,
    dmd.mangle.basic,
    dmd.mangle.cpp,
    dmd.mangle.cppwin,
    dmd.mtype,
    dmd.mustuse,
    dmd.nogc,
    dmd.nspace,
    dmd.ob,
    dmd.objc,
    dmd.opover,
    dmd.optimize,
    dmd.parse,
    dmd.pragmasem,
    dmd.printast,
    dmd.root.aav,
    dmd.root.array,
    dmd.root.bitarray,
    dmd.root.complex,
    dmd.root.ctfloat,
    dmd.root.env,
    dmd.root.file,
    dmd.root.filename,
    dmd.root.hash,
    dmd.root.longdouble,
    dmd.rootobject,
    dmd.root.optional,
    dmd.root.port,
    dmd.root.region,
    dmd.root.rmem,
    dmd.root.speller,
    dmd.root.string,
    dmd.root.stringtable,
    dmd.root.utf,
    dmd.safe,
    dmd.semantic2,
    dmd.semantic3,
    dmd.sideeffect,
    dmd.statement,
    dmd.statementsem,
    dmd.staticassert,
    dmd.staticcond,
    dmd.stmtstate,
    dmd.target,
    dmd.targetcompiler,
    dmd.templateparamsem,
    dmd.templatesem,
    dmd.timetrace,
    dmd.tokens,
    dmd.traits,
    dmd.typesem,
    dmd.typinf,
    dmd.utils,
    dmd.visitor,
    dmd.visitor.foreachvar,
    dmd.visitor.parsetime,
    dmd.visitor.permissive,
    dmd.visitor.postorder,
    dmd.visitor.statement_rewrite_walker,
    dmd.visitor.transitive,
);
